name: bmicaliculatorapp
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.8.1
  auto_size_text: ^2.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  fonts:
     - family: Roboto
       fonts:
         - asset: fonts/Roboto-Black.ttf
         - asset: fonts/Roboto-BlackItalic.ttf
         - asset: fonts/Roboto-Bold.ttf
         - asset: fonts/Roboto-BoldItalic.ttf
         - asset: fonts/Roboto-Italic.ttf
         - asset: fonts/Roboto-Light.ttf
         - asset: fonts/Roboto-LightItalic.ttf
         - asset: fonts/Roboto-Medium.ttf
         - asset: fonts/Roboto-MediumItalic.ttf
         - asset: fonts/Roboto-Black.ttf
         - asset: fonts/Roboto-Regular.ttf
         - asset: fonts/Roboto-Thin.ttf
         - asset: fonts/Roboto-ThinItalic.ttf

  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
